baseURL = "https://sqtrin.srht.site/"
languageCode = "it-IT"
title = "Square Terror Collective"
theme = "sqtrin"

[params]
  description = "Descrizione del collettivo"
  thumbnail = "/media/services/rss.jpg"
  rss = "/index.xml"
  favicon = "/media/services/shortcut.png"
  logo = "/media/interface/logo.png"
  author = "square_terror"
  [params.license]
    name = "BY-NC-SA 4.0"
    url = "/LICENSE"

[menus]
  [[menus.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "terrore quadrato"
    url = "/terrore-quadrato/"
    weight = 2
  [[menus.main]]
    name = "chi siamo"
    url = "/chi-siamo/"
    weight = 3
  [[menus.main]]
    name = "progetti"
    url = "/progetti/"
    weight = 4
  [[menus.main]]
    name = "contatti"
    url = "/contatti/"
    weight = 5
  [[menus.main]]
    name = "articoli"
    url = "/articoli/"
    weight = 6
